"""create itemdata table

Revision ID: 1ef0c2ea59d9
Revises: 
Create Date: 2024-07-11 11:49:22.879976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef0c2ea59d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemdata',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('long', sa.REAL(), nullable=True),
    sa.Column('userId', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemdata_id'), 'itemdata', ['id'], unique=False)
    op.create_index(op.f('ix_itemdata_lat'), 'itemdata', ['lat'], unique=False)
    op.create_index(op.f('ix_itemdata_long'), 'itemdata', ['long'], unique=False)
    op.create_index(op.f('ix_itemdata_price'), 'itemdata', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itemdata_price'), table_name='itemdata')
    op.drop_index(op.f('ix_itemdata_long'), table_name='itemdata')
    op.drop_index(op.f('ix_itemdata_lat'), table_name='itemdata')
    op.drop_index(op.f('ix_itemdata_id'), table_name='itemdata')
    op.drop_table('itemdata')
    # ### end Alembic commands ###
